[project]
name = "scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crossref-commons>=0.0.7",
    "scholarly>=1.7.11",
    "tqdm>=4.67.1",
]
